# Generated by Django 2.2.24 on 2025-02-13 11:19

from django.db import migrations

def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                'phonenumber': flat.owners_phonenumber,
                'pure_phone': flat.owner_pure_phone
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20250213_1414'),
    ]

    operations = [
        migrations.RunPython(fill_owners)
    ]
