# Generated by Django 2.2.24 on 2025-02-13 11:24

from django.db import migrations


def set_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner.flats.set(Flat.objects.filter(owner=owner.name, owners_phonenumber=owner.phonenumber))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250213_1419'),
    ]

    operations = [
        migrations.RunPython(set_flats)
    ]
